/**
 * POST /api/admin/seed-demo-lawyers
 * Auth: header X-Admin-Secret must match ADMIN_SECRET env var.
 *
 * One-time seed for the 0G APAC Hackathon demo personas. For each entry
 * in src/data/demoLawyers.ts:
 *   1. Skip if the wallet is already at status Verified or Pending on the
 *      LawyerRegistry contract (idempotent — safe to call repeatedly).
 *   2. Upload the persona metadata blob to 0G Storage (with isDemo flag
 *      and personaPrompt embedded).
 *   3. Call applyOnBehalf(wallet, rootHash) from the operator key.
 *   4. Call verifyLawyer(wallet) from the owner key (same key in our setup).
 *
 * Reports per-entry status. Pure setup, no user data touched.
 */

import { NextRequest, NextResponse } from "next/server";
import { uploadToStorage } from "@/lib/0g/storage";
import {
  serverApplyOnBehalf,
  serverVerifyLawyer,
} from "@/lib/contracts/LawyerRegistry";
import { getLawyerByWallet } from "@/lib/db/client";
import { DEMO_LAWYERS } from "@/data/demoLawyers";

export const maxDuration = 300;
export const runtime = "nodejs";

const ADMIN_SECRET = process.env.ADMIN_SECRET ?? "";

interface SeedReport {
  fullName: string;
  walletAddress: string;
  status: "skipped-already-verified" | "skipped-already-pending" | "seeded" | "failed";
  rootHash?: string;
  applyTx?: string;
  verifyTx?: string;
  error?: string;
}

export async function POST(req: NextRequest) {
  const secret = req.headers.get("x-admin-secret");
  if (!ADMIN_SECRET || secret !== ADMIN_SECRET) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const reports: SeedReport[] = [];

  for (const demo of DEMO_LAWYERS) {
    const r: SeedReport = {
      fullName: demo.fullName,
      walletAddress: demo.walletAddress,
      status: "failed",
    };

    try {
      // Idempotency: if the wallet already has a registry record, skip
      const existing = await getLawyerByWallet(demo.walletAddress);
      if (existing?.status === "verified") {
        r.status = "skipped-already-verified";
        reports.push(r);
        continue;
      }

      // Upload metadata blob
      const metadata = {
        walletAddress: demo.walletAddress,
        fullName: demo.fullName,
        email: demo.email,
        barNumber: demo.barNumber,
        jurisdiction: demo.jurisdiction,
        specializations: demo.specializations,
        yearsExperience: demo.yearsExperience,
        languages: demo.languages,
        bio: demo.bio,
        website: demo.website ?? "",
        serviceType: demo.serviceType,
        flatRateUSD: demo.flatRateUSD,
        hourlyRateUSD: demo.hourlyRateUSD,
        acceptsHires: demo.acceptsHires ?? true,
        isDemo: true,
        personaPrompt: demo.personaPrompt,
        // Disclaimer baked into the blob itself for transparency
        _disclaimer:
          "ZeroViza HACKATHON DEMO PERSONA. Replies generated by 0G Compute. Not a real licensed practitioner. 0G APAC Hackathon 2026.",
      };
      const buf = Buffer.from(JSON.stringify(metadata), "utf-8");
      const upload = await uploadToStorage(buf);
      r.rootHash = upload.rootHash;

      // Apply on chain (skip if already pending — applyOnBehalf is idempotent
      // in our contract: it overwrites metadataURI for non-Verified records)
      try {
        r.applyTx = await serverApplyOnBehalf(demo.walletAddress, upload.rootHash);
      } catch (applyErr) {
        // Already-pending isn't an error in our contract, but just in case
        const msg = applyErr instanceof Error ? applyErr.message : String(applyErr);
        if (!msg.includes("already") && !msg.includes("Pending")) throw applyErr;
        r.status = "skipped-already-pending";
        reports.push(r);
        continue;
      }

      // Verify
      r.verifyTx = await serverVerifyLawyer(demo.walletAddress);
      r.status = "seeded";
    } catch (err) {
      r.error = err instanceof Error ? err.message : String(err);
    }

    reports.push(r);
  }

  const summary = {
    total: reports.length,
    seeded: reports.filter((r) => r.status === "seeded").length,
    skipped: reports.filter((r) => r.status.startsWith("skipped")).length,
    failed: reports.filter((r) => r.status === "failed").length,
  };

  return NextResponse.json({ summary, reports });
}
