"use client";

import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { motion, AnimatePresence } from "framer-motion";
import Link from "next/link";
import type { Lawyer, ServiceType } from "@/types/lawyer";
import { SERVICE_TYPES } from "@/types/lawyer";
import { useWallet } from "@/hooks/useWallet";

interface HireReceipt {
  success: true;
  provider: string;
  providerWallet: string;
  agreedFeeUSD: number;
  isDemo: boolean;
  txHash: string;
  blockNumber: number;
  receiptHash: string;
  feeOG: string;
  caseAgentTokenId: string | null;
  explorerUrl: string;
  demoReply: string | null;
}

function HireModal({
  lawyer,
  onClose,
}: {
  lawyer: Lawyer;
  onClose: () => void;
}) {
  const { address, isDemo: isDemoWallet } = useWallet();
  const [taskDescription, setTaskDescription] = useState(
    `${lawyer.specializations[0] ?? "Immigration"} consultation`
  );
  const [fee, setFee] = useState<number>(lawyer.flatRateUSD ?? 75);
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [receipt, setReceipt] = useState<HireReceipt | null>(null);

  const canSubmit =
    !!address &&
    !isDemoWallet &&
    taskDescription.trim().length > 0 &&
    fee > 0 &&
    !submitting;

  async function handleHire() {
    if (!canSubmit) return;
    setSubmitting(true);
    setError(null);
    try {
      const res = await fetch("/api/agent/hire", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          walletAddress: address,
          providerWallet: lawyer.walletAddress,
          taskDescription: taskDescription.trim(),
          agreedFeeUSD: fee,
        }),
      });
      const data = (await res.json()) as HireReceipt & { error?: string };
      if (!res.ok || !data.success) {
        throw new Error(data.error ?? `Hire failed (${res.status})`);
      }
      setReceipt(data);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Hire failed");
    } finally {
      setSubmitting(false);
    }
  }

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      className="fixed inset-0 z-50 bg-black/40 flex items-center justify-center p-4"
      onClick={onClose}
    >
      <motion.div
        initial={{ scale: 0.95, y: 12 }}
        animate={{ scale: 1, y: 0 }}
        exit={{ scale: 0.95, y: 12 }}
        onClick={(e) => e.stopPropagation()}
        className="bg-white rounded-2xl max-w-md w-full max-h-[90vh] overflow-y-auto shadow-2xl"
      >
        {!receipt ? (
          <div className="p-6">
            <div className="flex items-start justify-between mb-3">
              <div>
                <p className="text-[10px] uppercase tracking-wider font-bold text-[#DC2626] mb-1">
                  Hire on chain via 0G
                </p>
                <h2 className="text-[#0F172A] font-black text-lg">{lawyer.fullName}</h2>
                <p className="text-[#64748B] text-xs">
                  {lawyer.serviceType} · {lawyer.jurisdiction}
                </p>
              </div>
              <button
                onClick={onClose}
                className="w-7 h-7 rounded-lg hover:bg-[#F1F5F9] flex items-center justify-center text-[#64748B]"
              >
                <svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2}>
                  <path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12" />
                </svg>
              </button>
            </div>

            {lawyer.isDemo && (
              <div className="mb-4 px-3 py-2 bg-amber-50 border border-amber-200 rounded-lg text-[11px] text-amber-900 leading-relaxed">
                <span className="font-bold">Hackathon demo persona.</span> The on-chain hire is real, but the reply is generated by 0G Compute — not a licensed practitioner.
              </div>
            )}

            <label className="block text-[#0F172A] text-xs font-bold mb-1 mt-2">
              Task description
            </label>
            <textarea
              value={taskDescription}
              onChange={(e) => setTaskDescription(e.target.value)}
              rows={3}
              placeholder="e.g. Review my US H-1B petition draft"
              className="w-full px-3 py-2 bg-[#F8FAFC] border border-[#E2E8F0] rounded-lg text-sm text-[#0F172A] focus:border-[#DC2626] focus:outline-none resize-none mb-3"
            />

            <label className="block text-[#0F172A] text-xs font-bold mb-1">
              Agreed fee (USD)
            </label>
            <input
              type="number"
              min={1}
              step={5}
              value={fee}
              onChange={(e) => setFee(Number(e.target.value) || 0)}
              className="w-full px-3 py-2 bg-[#F8FAFC] border border-[#E2E8F0] rounded-lg text-sm text-[#0F172A] focus:border-[#DC2626] focus:outline-none mb-3"
            />

            <div className="bg-[#0F172A] rounded-xl p-3 mb-4">
              <p className="text-[10px] uppercase tracking-wider font-bold text-[#94A3B8] mb-1">
                What happens on click
              </p>
              <ul className="text-[11px] text-white space-y-1 leading-relaxed">
                <li>1. Operator wallet sends 0.0001 0G to {lawyer.fullName.split(" ")[0]}&apos;s wallet</li>
                <li>2. Full hire receipt (you + task + $ + INFT id) is encoded in the tx calldata</li>
                <li>3. You get the tx hash + a clickable chainscan link</li>
                {lawyer.isDemo && <li>4. {lawyer.fullName.split(" ")[0]} replies via 0G Compute</li>}
              </ul>
            </div>

            {error && (
              <div className="mb-3 px-3 py-2 bg-red-50 border border-red-200 rounded-lg text-[11px] text-red-700">
                {error}
              </div>
            )}

            {!address || isDemoWallet ? (
              <p className="text-[#64748B] text-[11px] mb-3 text-center">
                Connect a real wallet to hire.
              </p>
            ) : null}

            <button
              onClick={handleHire}
              disabled={!canSubmit}
              className="w-full py-2.5 bg-[#DC2626] text-white text-sm font-bold rounded-xl hover:bg-[#B91C1C] transition-colors disabled:opacity-40 disabled:cursor-not-allowed flex items-center justify-center gap-2"
            >
              {submitting ? (
                <>
                  <span className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin" />
                  Sending tx on 0G…
                </>
              ) : (
                `Hire for $${fee}`
              )}
            </button>
            <p className="text-[#94A3B8] text-[10px] text-center mt-2">
              Operator pays gas. You hold no 0G tokens.
            </p>
          </div>
        ) : (
          <div className="p-6">
            <div className="flex items-center gap-2 mb-1">
              <div className="w-8 h-8 rounded-full bg-green-100 flex items-center justify-center">
                <svg className="w-4 h-4 text-green-700" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={3}>
                  <path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" />
                </svg>
              </div>
              <h2 className="text-[#0F172A] font-black text-lg">Hire confirmed on chain</h2>
            </div>
            <p className="text-[#64748B] text-xs mb-4">
              {receipt.provider} · ${receipt.agreedFeeUSD} · operator paid {receipt.feeOG} 0G in gas
            </p>

            <div className="space-y-2 mb-4">
              <div className="bg-[#F8FAFC] border border-[#E2E8F0] rounded-lg p-3">
                <p className="text-[10px] uppercase tracking-wider font-bold text-[#94A3B8] mb-1">
                  Tx hash
                </p>
                <p className="text-[11px] font-mono text-[#0F172A] break-all">{receipt.txHash}</p>
              </div>
              <div className="bg-[#F8FAFC] border border-[#E2E8F0] rounded-lg p-3">
                <p className="text-[10px] uppercase tracking-wider font-bold text-[#94A3B8] mb-1">
                  Receipt hash (keccak256 of calldata JSON)
                </p>
                <p className="text-[11px] font-mono text-[#0F172A] break-all">{receipt.receiptHash}</p>
              </div>
              {receipt.caseAgentTokenId && (
                <div className="bg-[#FEF2F2] border border-[#FECACA] rounded-lg p-3">
                  <p className="text-[10px] uppercase tracking-wider font-bold text-[#DC2626] mb-1">
                    Bound to Case Agent INFT
                  </p>
                  <p className="text-[11px] text-[#0F172A]">Token #{receipt.caseAgentTokenId}</p>
                </div>
              )}
            </div>

            <a
              href={receipt.explorerUrl}
              target="_blank"
              rel="noopener noreferrer"
              className="block w-full py-2.5 bg-[#DC2626] text-white text-sm font-bold rounded-xl hover:bg-[#B91C1C] transition-colors text-center mb-2"
            >
              View on 0G Scan →
            </a>
            <p className="text-[#94A3B8] text-[10px] text-center mb-4">
              Click the tx, scroll to &quot;Input Data&quot; — the full hire receipt is right there in plain JSON.
            </p>

            {receipt.demoReply && (
              <div className="bg-amber-50 border border-amber-200 rounded-lg p-3 mb-4">
                <p className="text-[10px] uppercase tracking-wider font-bold text-amber-900 mb-1.5">
                  Reply from {receipt.provider} (demo via 0G Compute)
                </p>
                <p className="text-[#0F172A] text-xs whitespace-pre-wrap leading-relaxed">
                  {receipt.demoReply}
                </p>
              </div>
            )}

            <button
              onClick={onClose}
              className="w-full py-2 border border-[#E2E8F0] text-[#475569] text-sm font-semibold rounded-lg hover:bg-[#F8FAFC] transition-colors"
            >
              Close
            </button>
          </div>
        )}
      </motion.div>
    </motion.div>
  );
}

const SPECIALIZATION_COLORS: Record<string, string> = {
  "Immigration": "bg-blue-100 text-blue-700",
  "Asylum": "bg-red-100 text-red-700",
  "Refugee Law": "bg-orange-100 text-orange-700",
  "Work Permits": "bg-green-100 text-green-700",
  "Family Reunification": "bg-purple-100 text-purple-700",
  "Deportation Defense": "bg-rose-100 text-rose-700",
  "Citizenship": "bg-yellow-100 text-yellow-700",
  "Student Visas": "bg-indigo-100 text-indigo-700",
};

function getSpecColor(spec: string): string {
  return SPECIALIZATION_COLORS[spec] ?? "bg-slate-100 text-slate-600";
}

async function fetchLawyers(): Promise<Lawyer[]> {
  const res = await fetch("/api/lawyers");
  if (!res.ok) throw new Error("Failed to load lawyers");
  const data = await res.json() as { lawyers: Lawyer[] };
  return data.lawyers;
}

export default function LawyersPage() {
  const [search, setSearch] = useState("");
  const [hireTarget, setHireTarget] = useState<Lawyer | null>(null);
  const [filterSpec, setFilterSpec] = useState("");
  const [filterType, setFilterType] = useState<"" | ServiceType>("");

  const { data: lawyers = [], isLoading, error } = useQuery({
    queryKey: ["lawyers"],
    queryFn: fetchLawyers,
    staleTime: 60_000,
  });

  const filtered = lawyers.filter((l) => {
    const q = search.toLowerCase();
    const matchesSearch =
      !q ||
      l.fullName.toLowerCase().includes(q) ||
      l.jurisdiction.toLowerCase().includes(q) ||
      l.languages.some((lang) => lang.toLowerCase().includes(q));
    const matchesSpec =
      !filterSpec || l.specializations.includes(filterSpec);
    const matchesType =
      !filterType || (l.serviceType ?? "Lawyer") === filterType;
    return matchesSearch && matchesSpec && matchesType;
  });

  const allSpecs = Array.from(
    new Set(lawyers.flatMap((l) => l.specializations))
  ).sort();

  return (
    <div className="flex-1 overflow-y-auto">
      <div className="max-w-5xl mx-auto px-4 sm:px-6 py-8">

        {/* Header */}
        <div className="mb-8">
          <div className="flex items-center justify-between flex-wrap gap-4">
            <div>
              <h1 className="text-2xl font-black text-[#0F172A]">Verified Service Providers</h1>
              <p className="text-[#64748B] text-sm mt-1">
                Lawyers, RCICs, OISC advisers, translators, evaluators and notaries verified on-chain
              </p>
            </div>
            <Link
              href="/lawyers/apply"
              className="inline-flex items-center gap-2 px-4 py-2 bg-[#DC2626] text-white text-sm font-semibold rounded-xl hover:bg-[#B91C1C] transition-colors shadow-sm"
            >
              <svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M9 12l2 2 4-4M7.835 4.697a3.42 3.42 0 001.946-.806 3.42 3.42 0 014.438 0 3.42 3.42 0 001.946.806 3.42 3.42 0 013.138 3.138 3.42 3.42 0 00.806 1.946 3.42 3.42 0 010 4.438 3.42 3.42 0 00-.806 1.946 3.42 3.42 0 01-3.138 3.138 3.42 3.42 0 00-1.946.806 3.42 3.42 0 01-4.438 0 3.42 3.42 0 00-1.946-.806 3.42 3.42 0 01-3.138-3.138 3.42 3.42 0 00-.806-1.946 3.42 3.42 0 010-4.438 3.42 3.42 0 00.806-1.946 3.42 3.42 0 013.138-3.138z" />
              </svg>
              Apply for Verification
            </Link>
          </div>

          {/* Search + filter */}
          <div className="flex flex-wrap gap-3 mt-5">
            <div className="relative flex-1 min-w-[200px]">
              <svg className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-[#94A3B8]" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2}>
                <circle cx={11} cy={11} r={8} />
                <path strokeLinecap="round" strokeLinejoin="round" d="M21 21l-4.35-4.35" />
              </svg>
              <input
                type="text"
                placeholder="Search by name, jurisdiction, language…"
                value={search}
                onChange={(e) => setSearch(e.target.value)}
                className="w-full pl-9 pr-4 py-2.5 bg-white border border-[#E2E8F0] rounded-xl text-sm text-[#0F172A] placeholder:text-[#94A3B8] focus:outline-none focus:border-[#DC2626] transition-colors"
              />
            </div>
            <select
              value={filterType}
              onChange={(e) => setFilterType(e.target.value as "" | ServiceType)}
              className="px-3 py-2.5 bg-white border border-[#E2E8F0] rounded-xl text-sm text-[#0F172A] focus:outline-none focus:border-[#DC2626] transition-colors"
            >
              <option value="">All service types</option>
              {SERVICE_TYPES.map((t) => (
                <option key={t} value={t}>{t}</option>
              ))}
            </select>
            {allSpecs.length > 0 && (
              <select
                value={filterSpec}
                onChange={(e) => setFilterSpec(e.target.value)}
                className="px-3 py-2.5 bg-white border border-[#E2E8F0] rounded-xl text-sm text-[#0F172A] focus:outline-none focus:border-[#DC2626] transition-colors"
              >
                <option value="">All specializations</option>
                {allSpecs.map((s) => (
                  <option key={s} value={s}>{s}</option>
                ))}
              </select>
            )}
          </div>
        </div>

        {/* Loading */}
        {isLoading && (
          <div className="flex items-center justify-center py-20 gap-3 text-[#94A3B8]">
            <div className="w-5 h-5 border-2 border-[#DC2626] border-t-transparent rounded-full animate-spin" />
            <span className="text-sm">Loading lawyers…</span>
          </div>
        )}

        {/* Error */}
        {error && (
          <div className="p-4 bg-red-50 border border-red-200 rounded-xl text-sm text-red-700">
            Failed to load lawyers. Please try again.
          </div>
        )}

        {/* Empty state */}
        {!isLoading && !error && filtered.length === 0 && (
          <div className="text-center py-20">
            <div className="w-16 h-16 rounded-2xl bg-[#F1F5F9] flex items-center justify-center mx-auto mb-4">
              <svg className="w-8 h-8 text-[#94A3B8]" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={1.5}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0z" />
              </svg>
            </div>
            <p className="text-[#0F172A] font-semibold">
              {lawyers.length === 0 ? "No verified lawyers yet" : "No results found"}
            </p>
            <p className="text-[#64748B] text-sm mt-1">
              {lawyers.length === 0
                ? "Be the first to apply for lawyer verification"
                : "Try adjusting your search or filter"}
            </p>
            {lawyers.length === 0 && (
              <Link
                href="/lawyers/apply"
                className="inline-flex items-center gap-2 mt-4 px-4 py-2 bg-[#DC2626] text-white text-sm font-semibold rounded-xl hover:bg-[#B91C1C] transition-colors"
              >
                Apply Now
              </Link>
            )}
          </div>
        )}

        {/* Lawyer grid */}
        {filtered.length > 0 && (
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
            {filtered.map((lawyer, i) => (
              <motion.div
                key={lawyer.id}
                initial={{ opacity: 0, y: 12 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: i * 0.04 }}
                className="bg-white border border-[#E2E8F0] rounded-2xl p-5 hover:border-[#DC2626]/30 hover:shadow-md transition-all"
              >
                {/* Header */}
                <div className="flex items-start gap-3 mb-3">
                  <div className="w-11 h-11 rounded-xl bg-[#DC2626]/10 flex items-center justify-center text-[#DC2626] font-black text-lg flex-shrink-0">
                    {lawyer.fullName.charAt(0).toUpperCase()}
                  </div>
                  <div className="min-w-0">
                    <div className="flex items-center gap-1.5">
                      <p className="text-[#0F172A] font-bold text-sm truncate">{lawyer.fullName}</p>
                      <svg className="w-4 h-4 text-[#DC2626] flex-shrink-0" viewBox="0 0 24 24" fill="currentColor">
                        <path fillRule="evenodd" d="M8.603 3.799A4.49 4.49 0 0112 2.25c1.357 0 2.573.6 3.397 1.549a4.49 4.49 0 013.498 1.307 4.491 4.491 0 011.307 3.497A4.49 4.49 0 0121.75 12a4.49 4.49 0 01-1.549 3.397 4.491 4.491 0 01-1.307 3.497 4.491 4.491 0 01-3.497 1.307A4.49 4.49 0 0112 21.75a4.49 4.49 0 01-3.397-1.549 4.491 4.491 0 01-3.497-1.307 4.491 4.491 0 01-1.307-3.497A4.49 4.49 0 012.25 12c0-1.357.6-2.573 1.549-3.397a4.49 4.49 0 011.307-3.497 4.49 4.49 0 013.497-1.307zm7.007 6.387a.75.75 0 10-1.22-.872l-3.236 4.53L9.53 12.22a.75.75 0 00-1.06 1.06l2.25 2.25a.75.75 0 001.14-.094l3.75-5.25z" clipRule="evenodd" />
                      </svg>
                    </div>
                    <p className="text-[#64748B] text-xs mt-0.5">{lawyer.jurisdiction}</p>
                    <div className="flex flex-wrap items-center gap-1 mt-1">
                      <span className="inline-block text-[9px] font-bold uppercase tracking-wider text-[#0F172A] bg-[#F1F5F9] border border-[#E2E8F0] rounded-full px-2 py-0.5">
                        {lawyer.serviceType ?? "Lawyer"}
                      </span>
                      {lawyer.isDemo && (
                        <span
                          className="inline-flex items-center gap-1 text-[9px] font-bold uppercase tracking-wider text-amber-900 bg-amber-100 border border-amber-300 rounded-full px-2 py-0.5"
                          title="This persona is a hackathon demo. Replies are generated by 0G Compute, not a real licensed practitioner."
                        >
                          <span className="w-1.5 h-1.5 rounded-full bg-amber-500" />
                          Demo · 0G Compute
                        </span>
                      )}
                      {lawyer.acceptsHires && (
                        <span className="inline-flex items-center gap-1 text-[9px] font-bold uppercase tracking-wider text-[#DC2626] bg-[#FEF2F2] border border-[#FECACA] rounded-full px-2 py-0.5">
                          <span className="w-1.5 h-1.5 rounded-full bg-[#DC2626] animate-pulse" />
                          Agent-hireable
                        </span>
                      )}
                      {lawyer.flatRateUSD !== undefined && lawyer.flatRateUSD > 0 && (
                        <span className="inline-block text-[9px] font-bold uppercase tracking-wider text-green-700 bg-green-50 border border-green-200 rounded-full px-2 py-0.5">
                          ${lawyer.flatRateUSD}/task
                        </span>
                      )}
                    </div>
                  </div>
                </div>

                {/* Bio */}
                {lawyer.bio && (
                  <p className="text-[#475569] text-xs leading-relaxed line-clamp-2 mb-3">
                    {lawyer.bio}
                  </p>
                )}

                {/* Stats */}
                <div className="flex items-center gap-3 mb-3 text-xs text-[#64748B]">
                  <span className="flex items-center gap-1">
                    <svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2}>
                      <path strokeLinecap="round" strokeLinejoin="round" d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" />
                    </svg>
                    {lawyer.yearsExperience}yr{lawyer.yearsExperience !== 1 ? "s" : ""}
                  </span>
                  <span className="flex items-center gap-1">
                    <svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2}>
                      <path strokeLinecap="round" strokeLinejoin="round" d="M3 5h12M9 3v2m1.048 9.5A18.022 18.022 0 016.412 9m6.088 9h7M11 21l5-10 5 10M12.751 5C11.783 10.77 8.07 15.61 3 18.129" />
                    </svg>
                    {lawyer.languages.slice(0, 2).join(", ")}
                    {lawyer.languages.length > 2 && ` +${lawyer.languages.length - 2}`}
                  </span>
                </div>

                {/* Specializations */}
                <div className="flex flex-wrap gap-1.5">
                  {lawyer.specializations.slice(0, 3).map((spec) => (
                    <span key={spec} className={`text-[10px] font-semibold px-2 py-0.5 rounded-full ${getSpecColor(spec)}`}>
                      {spec}
                    </span>
                  ))}
                  {lawyer.specializations.length > 3 && (
                    <span className="text-[10px] font-semibold px-2 py-0.5 rounded-full bg-slate-100 text-slate-500">
                      +{lawyer.specializations.length - 3} more
                    </span>
                  )}
                </div>

                {/* Actions: hire-on-chain (primary) + website link */}
                <div className="flex items-center gap-2 mt-4 pt-3 border-t border-[#F1F5F9]">
                  {lawyer.acceptsHires ? (
                    <button
                      onClick={() => setHireTarget(lawyer)}
                      className="flex-1 inline-flex items-center justify-center gap-1.5 px-3 py-1.5 bg-[#DC2626] text-white text-xs font-bold rounded-lg hover:bg-[#B91C1C] transition-colors"
                    >
                      <svg className="w-3 h-3" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2.5}>
                        <path strokeLinecap="round" strokeLinejoin="round" d="M13 10V3L4 14h7v7l9-11h-7z" />
                      </svg>
                      Hire on chain{lawyer.flatRateUSD ? ` · $${lawyer.flatRateUSD}` : ""}
                    </button>
                  ) : (
                    <span className="flex-1 text-center text-[10px] text-[#94A3B8] italic">
                      Not accepting agent hires
                    </span>
                  )}
                  {lawyer.website && (
                    <a
                      href={lawyer.website}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="inline-flex items-center gap-1 px-3 py-1.5 border border-[#E2E8F0] text-[#475569] text-xs font-semibold rounded-lg hover:border-[#DC2626] hover:text-[#DC2626] transition-colors"
                    >
                      <svg className="w-3 h-3" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2}>
                        <path strokeLinecap="round" strokeLinejoin="round" d="M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14" />
                      </svg>
                      Site
                    </a>
                  )}
                </div>
              </motion.div>
            ))}
          </div>
        )}

        <AnimatePresence>
          {hireTarget && (
            <HireModal lawyer={hireTarget} onClose={() => setHireTarget(null)} />
          )}
        </AnimatePresence>

        {/* Results count */}
        {!isLoading && lawyers.length > 0 && (
          <p className="text-center text-[#94A3B8] text-xs mt-6">
            {filtered.length} of {lawyers.length} verified lawyer{lawyers.length !== 1 ? "s" : ""}
          </p>
        )}
      </div>
    </div>
  );
}
